if(ENABLE_SDL3)
    find_package(SDL3 QUIET)
    if(SDL3_FOUND)
        message(STATUS "Found System SDL3")
        set(SDL3_TARGET SDL3::SDL3)
    else()
        # 没有找到系统中的 SDL3
        message(STATUS "System SDL3 not found")
        if (UNIX AND NOT APPLE)
        # UNIX下尝试使用 PkgConfig
            find_package(PkgConfig REQUIRED)
            if (PkgConfig_FOUND)
            #用于通过 pkg-config 工具检测和配置外部库，自动导入编译和链接参数
                pkg_check_modules(SDL3 REQUIRED IMPORTED_TARGET sdl3)
                if (TARGET PkgConfig::SDL3)
                    add_library(SDL3::SDL3 ALIAS PkgConfig::SDL3)
                    set(SDL3_TARGET SDL3::SDL3)
                    message(STATUS "Using PkgConfig SDL3")
                elseif()
                    message(STATUS "PkgConfig::SDL3 not found, fallback to vendored SDL3")
                    add_subdirectory(SDL SDL3)
                    set(SDL3_TARGET SDL3::SDL3)
                endif()
            elseif()
                message(STATUS "PkgConfig not found, fallback to vendored SDL3")
                add_subdirectory(SDL SDL3)
                set(SDL3_TARGET SDL3::SDL3)
            endif()
            
            add_library(SDL3::SDL3 ALIAS PkgConfig::SDL3)
            set(SDL3_TARGET SDL3::SDL3)
        elseif(APPLE)
        # APPLE下尝试使用 Homebrew
            find_package(SDL3 QUIET PATHS /opt/homebrew/opt/sdl3)

            if(SDL3_FOUND)
                set(SDL3_TARGET SDL3::SDL3)
                message(STATUS "Found SDL3 via Homebrew")
            else()
                message(WARNING "Homebrew SDL3 not found, fallback to vendored SDL3")
                add_subdirectory(SDL SDL3)
                set(SDL3_TARGET SDL3::SDL3)
            endif()
        else()
            message(STATUS "Using vendored SDL3 source code")
            add_subdirectory(SDL SDL3)
            set(SDL3_TARGET SDL3::SDL3)
        endif()
    endif()

    if(TARGET ${SDL3_TARGET})
        target_link_libraries(${PROJECT_NAME} PRIVATE ${SDL3_TARGET})
        message(STATUS "Linked ${PROJECT_NAME} with ${SDL3_TARGET}")
    else()
        message(FATAL_ERROR "SDL3 target ${SDL3_TARGET} not found")
    endif()
endif()
